// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTkfZ9YEGebqtQLYkfyYAywmlxWxJgIek',
    appId: '1:645974518800:web:e871888435e92e3a96ae95',
    messagingSenderId: '645974518800',
    projectId: 'training-app-13487',
    authDomain: 'training-app-13487.firebaseapp.com',
    storageBucket: 'training-app-13487.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNkGEa7MnU-AXfEJe38DIRoeKPYvuH78',
    appId: '1:645974518800:android:12c4776547ba49e196ae95',
    messagingSenderId: '645974518800',
    projectId: 'training-app-13487',
    storageBucket: 'training-app-13487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqO2X8ImFp8vS0FJAGaCmDQQxVF17cta0',
    appId: '1:645974518800:ios:144913ead7b28f3196ae95',
    messagingSenderId: '645974518800',
    projectId: 'training-app-13487',
    storageBucket: 'training-app-13487.appspot.com',
    iosClientId: '645974518800-mteds8kh94f4lavfrkouhcq1f5v1k1jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqO2X8ImFp8vS0FJAGaCmDQQxVF17cta0',
    appId: '1:645974518800:ios:144913ead7b28f3196ae95',
    messagingSenderId: '645974518800',
    projectId: 'training-app-13487',
    storageBucket: 'training-app-13487.appspot.com',
    iosClientId: '645974518800-mteds8kh94f4lavfrkouhcq1f5v1k1jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );
}
